package cw.coursework.Database;

/**
 * Created by pavlo on 20/02/2018.
 */

public enum DatabaseRes {
        DATABASE_CONNECTION_ERROR,

        DATABASE_ACCOUNT_NOT_FOUND,
        DATABASE_ACCOUNT_PASSWORD_INCORRECT,
        

        DATABASE_ACCOUNT_ALREADY_EXISTS,
        DATABASE_ACCOUNT_REGISTERED,
        DATABASE_ACCOUNT_LOGIN_SUCCESSFUL,

        DATABASE_LOGIN,
        DATABASE_REGISTER,

        DATABASE_SEND_ITEM,

        SUBSCRIPTON_TO_EVENTS,

        DATABASE_REQUEST_ITEMS,
        DATABASE_ITEM_SENT,
        DATABASE_MAKE_AN_OFFER,
        DATABASE_RECEIVE_COMMENTS,
        DATABASE_FACEBOOK_LOGIN





}

